package com.hzlgou.service.impl;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.hzlgou.config.AIConfig;
import com.hzlgou.model.Phrase;
import com.hzlgou.model.Word;
import com.hzlgou.service.AIService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.http.MediaType;
import reactor.core.publisher.Mono;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;

/**
 * AI服务实现类
 */
@Service
public class AIServiceImpl implements AIService {

    @Autowired
    private AIConfig aiConfig;

    private final WebClient webClient;

    public AIServiceImpl() {
        this.webClient = WebClient.builder()
                .build();
    }

    @Override
    public List<Word> buildHighFrequencyWordList(String text, int limit) {
        // 使用本地部署的DeepSeek生成高频词库
        try {
            String prompt = String.format("从以下文本中提取出前%d个高频单词，仅返回单词列表，用逗号分隔：\n\n%s", limit, text);
            String response = callDeepSeekAPI(prompt);
            
            List<Word> words = new ArrayList<>();
            String[] wordArray = response.split(",");
            
            for (String wordStr : wordArray) {
                String trimmedWord = wordStr.trim();
                if (!trimmedWord.isEmpty()) {
                    Word word = new Word();
                    word.setWord(trimmedWord);
                    word.setLemma(trimmedWord);
                    word.setPronunciation("/"); // 将通过语音合成获取
                    word.setDerivation("Generated by DeepSeek");
                    word.setTip("High frequency word");
                    words.add(word);
                }
            }
            
            return words;
        } catch (Exception e) {
            e.printStackTrace();
            // 如果API调用失败，返回模拟数据
            return getMockHighFrequencyWords(limit);
        }
    }
    
    private List<Word> getMockHighFrequencyWords(int limit) {
        List<Word> words = new ArrayList<>();
        String[] sampleWords = {"the", "of", "to", "and", "in", "a", "is", "that", "it", "for"};
        
        for (int i = 0; i < Math.min(limit, sampleWords.length); i++) {
            Word word = new Word();
            word.setWord(sampleWords[i]);
            word.setLemma(sampleWords[i]);
            word.setPronunciation("/");
            word.setDerivation("Common word in English");
            word.setTip("High frequency word");
            words.add(word);
        }
        
        return words;
    }

    @Override
    public List<Phrase> buildHighFrequencyPhraseList(String text, int limit) {
        // 使用本地部署的DeepSeek生成高频短语库
        try {
            String prompt = String.format("从以下文本中提取出前%d个高频短语（2-3个词），仅返回短语列表，用逗号分隔：\n\n%s", limit, text);
            String response = callDeepSeekAPI(prompt);
            
            List<Phrase> phrases = new ArrayList<>();
            String[] phraseArray = response.split(",");
            
            for (String phraseStr : phraseArray) {
                String trimmedPhrase = phraseStr.trim();
                if (!trimmedPhrase.isEmpty()) {
                    Phrase phrase = new Phrase();
                    phrase.setPhrase(trimmedPhrase);
                    phrase.setLen(trimmedPhrase.split(" ").length);
                    phrase.setMainIdx(0);
                    phrase.setDerivation("Generated by DeepSeek");
                    phrase.setTip("High frequency phrase");
                    phrases.add(phrase);
                }
            }
            
            return phrases;
        } catch (Exception e) {
            e.printStackTrace();
            // 如果API调用失败，返回模拟数据
            return getMockHighFrequencyPhrases(limit);
        }
    }
    
    private List<Phrase> getMockHighFrequencyPhrases(int limit) {
        List<Phrase> phrases = new ArrayList<>();
        String[] samplePhrases = {"in the", "of the", "to be", "it is", "for the", "on the", "you are", "that is", "at the", "have to"};
        
        for (int i = 0; i < Math.min(limit, samplePhrases.length); i++) {
            Phrase phrase = new Phrase();
            phrase.setPhrase(samplePhrases[i]);
            phrase.setLen(samplePhrases[i].split(" ").length);
            phrase.setMainIdx(0);
            phrase.setDerivation("Common phrase in English");
            phrase.setTip("High frequency phrase");
            phrases.add(phrase);
        }
        
        return phrases;
    }

    @Override
    public byte[] generateWordPronunciation(String word) {
        // 这里使用DeepSeek的文本转语音功能
        // 由于本地部署的DeepSeek可能没有TTS功能，暂时返回模拟音频数据
        // 在实际项目中，可以集成其他TTS服务或使用DeepSeek的TTS API
        String mockAudioData = "Mock audio data for word: " + word;
        return mockAudioData.getBytes();
    }

    @Override
    public byte[] generatePhrasePronunciation(String phrase) {
        // 这里使用DeepSeek的文本转语音功能
        // 由于本地部署的DeepSeek可能没有TTS功能，暂时返回模拟音频数据
        // 在实际项目中，可以集成其他TTS服务或使用DeepSeek的TTS API
        String mockAudioData = "Mock audio data for phrase: " + phrase;
        return mockAudioData.getBytes();
    }

    @Override
    public Map<String, Object> analyzeConjunctions(String sentence) {
        // 使用本地部署的DeepSeek分析连词
        try {
            String prompt = String.format("分析以下句子中的连词，返回JSON格式，包含word、type和function字段：\n\n%s", sentence);
            String response = callDeepSeekAPI(prompt);
            
            ObjectMapper mapper = new ObjectMapper();
            JsonNode rootNode = mapper.readTree(response);
            
            Map<String, Object> result = new HashMap<>();
            List<Map<String, String>> conjunctions = new ArrayList<>();
            
            JsonNode conjunctionsArray = rootNode.get("conjunctions");
            if (conjunctionsArray != null && conjunctionsArray.isArray()) {
                for (JsonNode conjNode : conjunctionsArray) {
                    Map<String, String> conjunction = new HashMap<>();
                    conjunction.put("word", conjNode.get("word").asText());
                    conjunction.put("type", conjNode.get("type").asText());
                    conjunction.put("function", conjNode.get("function").asText());
                    conjunctions.add(conjunction);
                }
            }
            
            result.put("sentence", sentence);
            result.put("conjunctions", conjunctions);
            result.put("analysis", rootNode.get("analysis").asText());
            
            return result;
        } catch (Exception e) {
            e.printStackTrace();
            // 如果API调用失败，返回模拟数据
            return getMockConjunctionAnalysis(sentence);
        }
    }
    
    private Map<String, Object> getMockConjunctionAnalysis(String sentence) {
        Map<String, Object> result = new HashMap<>();
        List<Map<String, String>> conjunctions = new ArrayList<>();
        
        // 模拟连词分析
        Map<String, String> conjunction = new HashMap<>();
        conjunction.put("word", "and");
        conjunction.put("type", "coordinating conjunction");
        conjunction.put("function", "连接两个并列成分");
        conjunctions.add(conjunction);
        
        result.put("sentence", sentence);
        result.put("conjunctions", conjunctions);
        result.put("analysis", "句子包含并列连词，连接两个并列的概念");
        
        return result;
    }

    @Override
    public String translateText(String text, String fromLang, String toLang) {
        // 使用本地部署的DeepSeek进行翻译
        try {
            String prompt = String.format("将以下文本从%s翻译成%s，仅返回翻译结果：\n\n%s", fromLang, toLang, text);
            return callDeepSeekAPI(prompt);
        } catch (Exception e) {
            e.printStackTrace();
            // 如果API调用失败，返回模拟翻译
            return "[翻译结果] " + text;
        }
    }

    @Override
    public Map<String, Object> getWordDetails(String word) {
        // 使用本地部署的DeepSeek获取单词详细信息
        try {
            String prompt = String.format("获取以下单词的详细信息，返回JSON格式，必须包含以下字段：\n" +
                    "- word: 单词本身\n" +
                    "- pronunciation: 发音\n" +
                    "- meaning: 词义（数组形式，每个元素是一个词义）\n" +
                    "- partOfSpeech: 词性\n" +
                    "- examples: 例句数组，每个元素包含en(英文)和zh(中文翻译)\n" +
                    "- synonyms: 同义词数组\n" +
                    "- antonyms: 反义词数组\n" +
                    "- derivatives: 派生词数组\n" +
                    "- phrases: 相关短语数组，每个元素包含en(英文)和zh(中文翻译)\n\n%s", word);
            String response = callDeepSeekAPI(prompt);
            
            ObjectMapper mapper = new ObjectMapper();
            return mapper.readValue(response, new com.fasterxml.jackson.core.type.TypeReference<Map<String, Object>>() {});
        } catch (Exception e) {
            e.printStackTrace();
            // 如果API调用失败，返回模拟数据
            Map<String, Object> details = new HashMap<>();
            details.put("word", word);
            details.put("pronunciation", "/wɜːrd/");
            details.put("meaning", List.of("单词，字", "词的含义", "言语"));
            details.put("partOfSpeech", "noun");
            
            List<Map<String, String>> examples = new ArrayList<>();
            Map<String, String> example1 = new HashMap<>();
            example1.put("en", "This is a common word.");
            example1.put("zh", "这是一个常见的单词。");
            examples.add(example1);
            
            Map<String, String> example2 = new HashMap<>();
            example2.put("en", "He said a few kind words.");
            example2.put("zh", "他说了几句友好的话。");
            examples.add(example2);
            
            details.put("examples", examples);
            details.put("synonyms", List.of("term", "expression", "vocabulary"));
            details.put("antonyms", List.of("phrase", "sentence"));
            details.put("derivatives", List.of("wordy", "wording", "wordless"));
            
            List<Map<String, String>> phrases = new ArrayList<>();
            Map<String, String> phrase1 = new HashMap<>();
            phrase1.put("en", "word by word");
            phrase1.put("zh", "逐字地");
            phrases.add(phrase1);
            
            Map<String, String> phrase2 = new HashMap<>();
            phrase2.put("en", "in a word");
            phrase2.put("zh", "总而言之");
            phrases.add(phrase2);
            
            details.put("phrases", phrases);
            
            return details;
        }
    }

    @Override
    public Map<String, Object> getPhraseDetails(String phrase) {
        // 使用本地部署的DeepSeek获取短语详细信息
        try {
            String prompt = String.format("获取以下短语的详细信息，包括meaning、usage和example字段，返回JSON格式：\n\n%s", phrase);
            String response = callDeepSeekAPI(prompt);
            
            ObjectMapper mapper = new ObjectMapper();
            return mapper.readValue(response, new com.fasterxml.jackson.core.type.TypeReference<Map<String, Object>>() {});
        } catch (Exception e) {
            e.printStackTrace();
            // 如果API调用失败，返回模拟数据
            Map<String, Object> details = new HashMap<>();
            details.put("phrase", phrase);
            details.put("meaning", "常用短语");
            details.put("usage", "在日常英语中经常使用");
            details.put("example", "This phrase is commonly used.");
            
            return details;
        }
    }
    
    /**
     * 调用DeepSeek API的通用方法
     */
    private String callDeepSeekAPI(String prompt) throws IOException, InterruptedException, ExecutionException {
        // 创建请求体
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("model", aiConfig.getDeepseek().getModel());
        requestBody.put("temperature", 0.7);
        requestBody.put("max_tokens", 1000);
        
        List<Map<String, String>> messages = new ArrayList<>();
        Map<String, String> systemMessage = new HashMap<>();
        systemMessage.put("role", "system");
        systemMessage.put("content", "你是一个英语学习助手，需要帮助用户学习英语单词和短语。");
        messages.add(systemMessage);
        
        Map<String, String> userMessage = new HashMap<>();
        userMessage.put("role", "user");
        userMessage.put("content", prompt);
        messages.add(userMessage);
        
        requestBody.put("messages", messages);
        
        // 创建ObjectMapper用于JSON处理
        ObjectMapper mapper = new ObjectMapper();
        
        // 异步调用DeepSeek API
        CompletableFuture<String> future = webClient.post()
            .uri(aiConfig.getDeepseek().getApiUrl() + "/chat/completions")
            .header("Authorization", "Bearer " + aiConfig.getDeepseek().getApiKey())
            .contentType(MediaType.APPLICATION_JSON)
            .bodyValue(requestBody)
            .retrieve()
            .bodyToMono(String.class)
            .toFuture();
        
        // 等待结果
        String response = future.get();
        
        // 解析响应
        JsonNode rootNode = mapper.readTree(response);
        return rootNode.path("choices").get(0).path("message").path("content").asText();
    }
}
